itsnporg/Basic-Programs

Python/generate_fib.py
This is a simple Fibonacci series generator in Python
=> Added a simple Fibonacci series generator

Python/habittracker.py
=> habit-tracker

C/simple_login_system.c
Hello There! 
I added the simple login system which is able to do both sign up and login using file handling in C.
=> Adding new simple_login_system using C programming

Golang/http_serve.go
=> add golang script

JavaScript/fibonacciSeries.js
summary: 
added basic JavaScript program to print Fibonacci series.
=> Fix #25 add basic JavaScript program for Fibonacci series

JavaScript/ML.js
This program can detect the sound of chainsaw, forest fire and help in detecting Illegal Logging and Illegal Poaching.
=> Audio Classification program ML.js

C/insertion_sort.c, C/leap_year.c, C/linear_search.c, C/matrix_calculator.c, C/matrix_viewer.c, C/max_min_array.c, C/merge_sort_full.c
Added some basic C programs on C directory
=> added C programs

Python/validate_password_strength.py
Added Method to check if the password is valid as per the required strength.
=> Added validate_password_strength.py

JavaScript/ChessBoard.js
create simple chessboard layout using # and space
=> chessboard program

Golang/Password Generator/password.go
Cryptographically secured password generation, more memorable than random character strings
=> Cryptographically secure password generator

Python/bubble_sort.py, Python/insertion_sort.py, Python/selection_sort.py
Thanks in advance for merging my contributions 😀
=> Python Sorting Algorithms

JavaScript/SuperHero.js
It tells what hero you would have been in different Super Hero universes
=> Added SuperHero.js

Java/PasswordGenerator.java
Password Generator that creates a combination of characters as specified by the user.
=> Added Password Generator

C++/MergeSort.cpp
Time Complexity : O(nlog(n))
Space Complexity: O(n)
Merge Sort is fastest conventional algorithm that sorts the array.
=> Added Merge Sort Algorithm using Recursion

Python/doublyLinkedList.py
I've added Doubly Linked List in Python
=> doublyLinkedList added

C/Password validator.c
=> c programm that validate passwords

JavaScript/Learn_async_await.js
Made a javascript file with async and await code with explained comments
=> async and await in javascript

Python/flask_api.py, Python/hamroPatro.py, Python/regex.py
=> simple pattern matching using re

C++/Longest-Special-Subsequence.cpp.cpp
You are given a string s of the length n consisting of only lowercase English alphabets. You are also given an integer k.
If the two consecutive characters in a subsequence have a difference that is no more than k, then it is called a special subsequence. Find the length of the longest special subsequence.
1
7 2 afcbedg
4
One of the longest special sequence present in "afcbedf" is a, c, b, d. 
It is special because |a-c|<=2, |c-b|<=2 and |b-d|<=2
=> Longest Special Subsequence

Python/Pacman.py
I made this Pacman game using Python.
=> Pacman game in Python

JavaScript/Calculator/index.html, JavaScript/Calculator/index.js, JavaScript/Calculator/style.css
This calculator is capable of performing basic mathematical functions.
=> Calculator using js,html and css

C++/Numerical_integration_using_function.cpp, C++/Numerical_integration_using_points.cpp
=> Numerical integration using initial and final points and function

Java/BinaryTreePreorderTraversal.java
Binary Tree Preorder Traversal
Iterative Approach using a Stack and a list.
=> Add Binary Tree Preorder Traversal

Typescript/dsa/Stack/StackOperations.ts
did the basic stack operation in typescript
=> Stack Operations push,pop,peek and print Stack in TypeScript

Java/BinaryTreePostorderTraversal.java
Binary Tree PostOrder Traversal
Iterative approach, Using 2 Stack and a list.
=> Add Binary Tree PostOrder Traversal

Python/yt_download.py
the script allows users t download their preferred youtube videos
=> added a script to download YouTube videos

C/Armstrong Number
This is my first Hacktoberfest pull request.
=> Create Armstrong Number
